apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-and-ping-claim
spec:
  storageClassName: log-and-ping-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
